# Generated by Django 5.1.2 on 2024-12-17 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0004_rename_created_at_news_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
